services:
  portfolio-2026-mysql:
    image: mysql:8.0
    container_name: portfolio-mysql-prod
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio-2026-network

  portfolio-2026-backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.prod
    container_name: portfolio-backend-prod
    # restart: always
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8.0&charset=utf8mb4
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
    depends_on:
      portfolio-2026-mysql:
        condition: service_healthy
    networks:
      - portfolio-2026-network
    volumes:
      - ./apps/backend/public:/var/www/html/public

  portfolio-2026-frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-/api}
        NEXT_SERVER_HOST: ${NEXT_SERVER_HOST}
    container_name: portfolio-frontend-prod
    # restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-/api}
      NEXT_SERVER_HOST: ${NEXT_SERVER_HOST}
    networks:
      - portfolio-2026-network

  portfolio-2026-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: portfolio-nginx-prod
    # restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./apps/backend/public:/var/www/html/public:ro
    depends_on:
      - portfolio-2026-frontend
      - portfolio-2026-backend
    networks:
      - portfolio-2026-network
      - npm

networks:
  portfolio-2026-network:
    driver: bridge
  npm:
    external: true
    name: nginx-proxy-manager-stack_default

volumes:
  mysql-data-prod:
