services:
  symfony:
    container_name: portfolio_symfony
    build: ./docker/symfony
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
    volumes:
      - ./:/var/www/html:z
    depends_on:
      - mysql
    networks:
      - default
    user: 1000:1000

  nginx:
    container_name: portfolio_nginx
    build: ./docker/nginx
    depends_on:
      - symfony
    volumes:
      - ./:/var/www/html:z
    networks:
      - default
      - npm
      
  mysql:
    container_name: portfolio_mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

volumes:
  mysql_data:

networks:
  default:
    driver: bridge
  npm:
    external: true
    name: nginx-proxy-manager-stack_default