import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const moonGet = localFont({
  src: './fonts/moon_get/moon_get-Heavy.ttf',
  variable: '--font-moon-get'
})

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${moonGet.variable} ${comfortaa.variable} h-full scroll-smooth antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
