server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        proxy_set_header X-Forwarded-Proto $scheme;
        try_files $uri /index.php$is_args$args;
    }

    location = /2026-CV_Yohann-RENAULD.pdf {
        add_header X-Robots-Tag "noindex, nofollow";
    }

    location ~ \.php$ {
        fastcgi_pass portfolio_symfony:9001;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }
}
