import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import localFont from 'next/font/local'

import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";

import "./globals.css";

const moonGet = localFont({
  src: './fonts/moon_get/moon_get-Heavy.ttf',
  variable: '--font-moon-get'
})

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${moonGet.variable} ${comfortaa.variable} h-full scroll-smooth antialiased`}
    >
      <body className="
        relative
        mx-auto
        min-h-dvh
        max-w-[1920px]
        flex flex-col
        bg-background/50
        shadow-[0_0_50px_rgba(56,132,35,0.15),0_0_20px_rgba(56,132,35,0.2),0_0_15px_rgba(56,132,35,0.3)]
      ">
        <Header />
        <main className="relative bg-background min-h-screen z-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
