import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import localFont from 'next/font/local'

import Footer from "@/components/ui/footer";

import "./globals.css";

const moonGet = localFont({
  src: './fonts/moon_get/moon_get-Heavy.ttf',
  variable: '--font-moon-get'
})

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${moonGet.variable} ${comfortaa.variable} h-full scroll-smooth antialiased`}
    >
      <body className="relative min-h-dvh flex flex-col bg-black mx-auto max-w-[1920px]">
        <main className="relative bg-background min-h-screen z-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
